topics:
- "The heart-stopping gamble of a Roman 'Plagiarius' (kidnapper) in the slums of Subura\
  \ who snatched the wrong child\u2014a runaway slave belonging to a ruthless Praetorian\
  \ Prefect\u2014and had only hours to return him undetected before the urban cohorts\
  \ burned the entire block down."
- The high-tension ordeal of a Byzantine 'Pyrotechnikos' (Greek Fire mixer) in the
  secret workshops of Constantinople, who had to manually extinguish a chemical leak
  of the highly unstable incendiary liquid before a single spark vaporized his entire
  family and the harbor.
