topics:
- 'The agonizing death of Heracles: how a dying centaur''s trick convinced his desperate
  wife, Deianira, to poison him with a cloak soaked in burning Hydra venom to prevent
  his infidelity'
