topics:
- The desperate, final audio recording of Lars Mittank, a young German tourist who
  fled a Bulgarian airport in sheer terror, leaving all his belongings behind to run
  into a dense forest, never to be seen again.
- "The chilling case of the Yuba County Five\u2014five young men who attended a basketball\
  \ game in 1978, only to abandon their perfectly functioning car high in a snowy\
  \ mountain forest, leading to a bizarre and agonizing tragedy in an abandoned forest\
  \ service trailer."
- The mysterious, agonizing death of Netta Fornario on the mystical, remote Scottish
  island of Iona in 1929, where she was found on a hillside next to a cryptic cross
  carved into the turf, clad only in a black cloak with her jewelry mysteriously intact.
