topics:
- "The chilling case of the Yuba County Five\u2014five young men who attended a basketball\
  \ game in 1978, only to abandon their perfectly functioning car high in a snowy\
  \ mountain forest, leading to a bizarre and agonizing tragedy in an abandoned forest\
  \ service trailer."
