topics:
- 'The agonizing gamble of Dr. Eugene Lazowski: The Polish doctor who created a fake
  typhus epidemic by injecting thousands of villagers with a harmless dead bacterium,
  risking execution by the Gestapo to save entire towns from being sent to concentration
  camps.'
- 'The fatal hesitation of General Charles de Lanrezac: The French commander who defied
  his own Supreme Commander''s suicidal offensive doctrine at the Battle of Charleroi
  in 1914, risking his career and being branded a coward to save the entire French
  Army from annihilation.'
- "The claustrophobic nightmare of Corporal Hiroo Onoda\u2019s final night in the\
  \ jungle: A vivid look at the psychological breaking point of the Japanese holdout\
  \ who spent 29 years waging a solo guerrilla war in the Philippine jungle, refusing\
  \ to believe WWII had ended."
- 'The desperate, secret flight of Princess Mafalda of Savoy: How the daughter of
  the Italian King was lured into a trap by the Gestapo on the pretext of a phone
  call from her missing husband, ending in her tragic imprisonment in Buchenwald.'
